// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/np4.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_ASYNC_MSG      MessageType = 0
	MessageType_SYNC_REQUEST   MessageType = 1
	MessageType_SYNC_RESPONSE  MessageType = 2
	MessageType_BROADCAST      MessageType = 3
	MessageType_FILE_CHUNK     MessageType = 4
	MessageType_MIX_CTRL       MessageType = 5
	MessageType_KEY_EXCHANGE   MessageType = 6
	MessageType_PEER_DISCOVERY MessageType = 7
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "ASYNC_MSG",
		1: "SYNC_REQUEST",
		2: "SYNC_RESPONSE",
		3: "BROADCAST",
		4: "FILE_CHUNK",
		5: "MIX_CTRL",
		6: "KEY_EXCHANGE",
		7: "PEER_DISCOVERY",
	}
	MessageType_value = map[string]int32{
		"ASYNC_MSG":      0,
		"SYNC_REQUEST":   1,
		"SYNC_RESPONSE":  2,
		"BROADCAST":      3,
		"FILE_CHUNK":     4,
		"MIX_CTRL":       5,
		"KEY_EXCHANGE":   6,
		"PEER_DISCOVERY": 7,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_np4_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_np4_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_np4_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_OK             ErrorCode = 0
	ErrorCode_INVALID_FORMAT ErrorCode = 1
	ErrorCode_DECRYPT_FAILED ErrorCode = 2
	ErrorCode_KEY_MISMATCH   ErrorCode = 3
	ErrorCode_TTL_EXPIRED    ErrorCode = 4
	ErrorCode_BATCH_FULL     ErrorCode = 5
	ErrorCode_UNKNOWN_NODE   ErrorCode = 6
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "INVALID_FORMAT",
		2: "DECRYPT_FAILED",
		3: "KEY_MISMATCH",
		4: "TTL_EXPIRED",
		5: "BATCH_FULL",
		6: "UNKNOWN_NODE",
	}
	ErrorCode_value = map[string]int32{
		"OK":             0,
		"INVALID_FORMAT": 1,
		"DECRYPT_FAILED": 2,
		"KEY_MISMATCH":   3,
		"TTL_EXPIRED":    4,
		"BATCH_FULL":     5,
		"UNKNOWN_NODE":   6,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_np4_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_np4_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_np4_proto_rawDescGZIP(), []int{1}
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Header        *Header                `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_np4_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_np4_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_np4_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Envelope) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=np4.MessageType" json:"type,omitempty"`
	DestId        []byte                 `protobuf:"bytes,2,opt,name=dest_id,json=destId,proto3" json:"dest_id,omitempty"`
	SenderId      []byte                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ttl           uint32                 `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Version       uint32                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_np4_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_np4_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_np4_proto_rawDescGZIP(), []int{1}
}

func (x *Header) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_ASYNC_MSG
}

func (x *Header) GetDestId() []byte {
	if x != nil {
		return x.DestId
	}
	return nil
}

func (x *Header) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

func (x *Header) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetTtl() uint32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type Payload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	SessionKey    []byte                 `protobuf:"bytes,2,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	HopCount      uint32                 `protobuf:"varint,3,opt,name=hop_count,json=hopCount,proto3" json:"hop_count,omitempty"`
	NextHop       []byte                 `protobuf:"bytes,4,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payload) Reset() {
	*x = Payload{}
	mi := &file_proto_np4_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_np4_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_proto_np4_proto_rawDescGZIP(), []int{2}
}

func (x *Payload) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Payload) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

func (x *Payload) GetHopCount() uint32 {
	if x != nil {
		return x.HopCount
	}
	return 0
}

func (x *Payload) GetNextHop() []byte {
	if x != nil {
		return x.NextHop
	}
	return nil
}

type MixBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       uint64                 `protobuf:"varint,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	Messages      []*Envelope            `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Proof         []byte                 `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MixBatch) Reset() {
	*x = MixBatch{}
	mi := &file_proto_np4_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MixBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MixBatch) ProtoMessage() {}

func (x *MixBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_np4_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MixBatch.ProtoReflect.Descriptor instead.
func (*MixBatch) Descriptor() ([]byte, []int) {
	return file_proto_np4_proto_rawDescGZIP(), []int{3}
}

func (x *MixBatch) GetBatchId() uint64 {
	if x != nil {
		return x.BatchId
	}
	return 0
}

func (x *MixBatch) GetMessages() []*Envelope {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *MixBatch) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_proto_np4_proto protoreflect.FileDescriptor

const file_proto_np4_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/np4.proto\x12\x03np4\"g\n" +
	"\bEnvelope\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12#\n" +
	"\x06header\x18\x03 \x01(\v2\v.np4.HeaderR\x06header\"\xae\x01\n" +
	"\x06Header\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.np4.MessageTypeR\x04type\x12\x17\n" +
	"\adest_id\x18\x02 \x01(\fR\x06destId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\fR\bsenderId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\rR\x03ttl\x12\x18\n" +
	"\aversion\x18\x06 \x01(\rR\aversion\"|\n" +
	"\aPayload\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1f\n" +
	"\vsession_key\x18\x02 \x01(\fR\n" +
	"sessionKey\x12\x1b\n" +
	"\thop_count\x18\x03 \x01(\rR\bhopCount\x12\x19\n" +
	"\bnext_hop\x18\x04 \x01(\fR\anextHop\"f\n" +
	"\bMixBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\x04R\abatchId\x12)\n" +
	"\bmessages\x18\x02 \x03(\v2\r.np4.EnvelopeR\bmessages\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\fR\x05proof*\x94\x01\n" +
	"\vMessageType\x12\r\n" +
	"\tASYNC_MSG\x10\x00\x12\x10\n" +
	"\fSYNC_REQUEST\x10\x01\x12\x11\n" +
	"\rSYNC_RESPONSE\x10\x02\x12\r\n" +
	"\tBROADCAST\x10\x03\x12\x0e\n" +
	"\n" +
	"FILE_CHUNK\x10\x04\x12\f\n" +
	"\bMIX_CTRL\x10\x05\x12\x10\n" +
	"\fKEY_EXCHANGE\x10\x06\x12\x12\n" +
	"\x0ePEER_DISCOVERY\x10\a*\x80\x01\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x12\n" +
	"\x0eINVALID_FORMAT\x10\x01\x12\x12\n" +
	"\x0eDECRYPT_FAILED\x10\x02\x12\x10\n" +
	"\fKEY_MISMATCH\x10\x03\x12\x0f\n" +
	"\vTTL_EXPIRED\x10\x04\x12\x0e\n" +
	"\n" +
	"BATCH_FULL\x10\x05\x12\x10\n" +
	"\fUNKNOWN_NODE\x10\x06B\x1aZ\x18Np4Protocol/go/pkg/protob\x06proto3"

var (
	file_proto_np4_proto_rawDescOnce sync.Once
	file_proto_np4_proto_rawDescData []byte
)

func file_proto_np4_proto_rawDescGZIP() []byte {
	file_proto_np4_proto_rawDescOnce.Do(func() {
		file_proto_np4_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_np4_proto_rawDesc), len(file_proto_np4_proto_rawDesc)))
	})
	return file_proto_np4_proto_rawDescData
}

var file_proto_np4_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_np4_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_np4_proto_goTypes = []any{
	(MessageType)(0), // 0: np4.MessageType
	(ErrorCode)(0),   // 1: np4.ErrorCode
	(*Envelope)(nil), // 2: np4.Envelope
	(*Header)(nil),   // 3: np4.Header
	(*Payload)(nil),  // 4: np4.Payload
	(*MixBatch)(nil), // 5: np4.MixBatch
}
var file_proto_np4_proto_depIdxs = []int32{
	3, // 0: np4.Envelope.header:type_name -> np4.Header
	0, // 1: np4.Header.type:type_name -> np4.MessageType
	2, // 2: np4.MixBatch.messages:type_name -> np4.Envelope
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_np4_proto_init() }
func file_proto_np4_proto_init() {
	if File_proto_np4_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_np4_proto_rawDesc), len(file_proto_np4_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_np4_proto_goTypes,
		DependencyIndexes: file_proto_np4_proto_depIdxs,
		EnumInfos:         file_proto_np4_proto_enumTypes,
		MessageInfos:      file_proto_np4_proto_msgTypes,
	}.Build()
	File_proto_np4_proto = out.File
	file_proto_np4_proto_goTypes = nil
	file_proto_np4_proto_depIdxs = nil
}
